service: aws-eks-spot-serverless-demo

package:
   individually: true

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  variableSyntax: "\\${((?!AWS)[ ~:a-zA-Z0-9._'\",\\-\\/\\(\\)]+?)}"

functions:
  VideoUploadLambdaFunction:
    handler: upload_video/upload_video.handler
    package:
      include:
        - upload_video/**
        - .kube/**
        - bin/**
      exclude:
        - ./**
    events:
      - s3:
          bucket: "${self:service}-${self:provider.stage}-uploads"
          event: s3:ObjectCreated:*
  VideoThumbnailLambdaFunction:
    handler: upload_thumbnail/upload_thumbnail.handler
    package:
      include:
        - upload_thumbnail/**
      exclude:
        - ./**
    events:
      - s3:
          bucket: "${self:service}-${self:provider.stage}-thumbnails"
          event: s3:ObjectCreated:*

resources:
  Resources:
    KubernetesClusterVPC:
      Type: AWS::EC2::VPC
      Properties: 
        CidrBlock: "10.0.0.0/16"
        EnableDnsSupport: true
        EnableDnsHostnames: true
        Tags:
          - 
            Key: Name
            Value: ${self:service}-${self:provider.stage}
    KubernetesClusterSubnetA:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: KubernetesClusterVPC
        CidrBlock: 10.0.0.0/24
        AvailabilityZone: "us-east-1a"
        Tags:
          -
            Key: Name
            Value: ${self:service}-${self:provider.stage}-subnet-a
    KubernetesClusterSubnetB:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: KubernetesClusterVPC
        CidrBlock: 10.0.1.0/24
        AvailabilityZone: "us-east-1b"
        Tags:
          -
            Key: Name
            Value: ${self:service}-${self:provider.stage}
    KubernetesClusterInternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
        Tags:
          -
            Key: Name
            Value: ${self:service}-${self:provider.stage}
    KubernetesClusterInternetGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties: 
        InternetGatewayId:
          Ref: KubernetesClusterInternetGateway
        VpcId:
          Ref: KubernetesClusterVPC
    KubernetesClusterInternetGatewayRouteTable:
      Type: AWS::EC2::RouteTable
      Properties: 
        VpcId:
          Ref: KubernetesClusterVPC
        Tags:
          -
            Key: Name
            Value: ${self:service}-${self:provider.stage}
    KubernetesClusterInternetGatewayToInternetRoute:
      Type: AWS::EC2::Route
      DependsOn: KubernetesClusterInternetGateway
      Properties:
        RouteTableId:
          Ref: KubernetesClusterInternetGatewayRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: KubernetesClusterInternetGateway
    KubernetesClusterSubnetAtoInternetRouteAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties: 
        RouteTableId:
          Ref: KubernetesClusterInternetGatewayRouteTable
        SubnetId:
          Ref: KubernetesClusterSubnetA
    KubernetesClusterSubnetBtoInternetRouteAssociation:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties: 
        RouteTableId:
          Ref: KubernetesClusterInternetGatewayRouteTable
        SubnetId:
          Ref: KubernetesClusterSubnetB
    EksKubernetesServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: EksKubernetesServiceRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - eks.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/AmazonEKSClusterPolicy'
          - 'arn:aws:iam::aws:policy/AmazonEKSServicePolicy'
    KubernetesClusterMasterSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow EKS Cluster communication with worker nodes
        VpcId:
          Ref: KubernetesClusterVPC
        SecurityGroupEgress:
          - IpProtocol: -1
            FromPort: 0
            ToPort: 0
            CidrIp: 0.0.0.0/0
        Tags:
          -
            Key: Name
            Value: ${self:service}-${self:provider.stage}
    # OPTIONAL: Allow inbound traffic from your local workstation external IP
    #           to the Kubernetes. You will need to replace A.B.C.D below with
    #           your real IP. Services like icanhazip.com can help you find this.
    KubernetesClusterMasterFromWorkstationSecurityGroupRule:
      Type: AWS::EC2::SecurityGroupIngress
      Properties: 
        # CidrIp: A.B.C.D/32
        CidrIp: 138.68.101.60/32
        Description: Allow workstation to communicate with the EKS cluster API Server
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
        GroupId:
          Ref: KubernetesClusterMasterSecurityGroup
    KubernetesCluster:
      Type: "AWS::EKS::Cluster"
      Properties:
        Name: ${self:service}-${self:provider.stage}
        ResourcesVpcConfig:
          SecurityGroupIds:
            - Ref: KubernetesClusterMasterSecurityGroup
          SubnetIds:
            - Ref: KubernetesClusterSubnetA
            - Ref: KubernetesClusterSubnetB
        RoleArn:
          Fn::GetAtt: [ EksKubernetesServiceRole, Arn ]
        Version: "1.10"
    # EKS Nodes
    NodeInstanceRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - ec2.amazonaws.com
              Action: sts:AssumeRole
        Path: "/"
        Policies:
          - 
            PolicyName: node
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ec2:Describe*
                    - ecr:GetAuthorizationToken
                    - ecr:BatchCheckLayerAvailability
                    - ecr:GetDownloadUrlForLayer
                    - ecr:GetRepositoryPolicy
                    - ecr:DescribeRepositories
                    - ecr:ListImages
                    - ecr:BatchGetImage
                  Resource: "*"
          - 
            PolicyName: cni
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - 
                  Effect: Allow
                  Action:
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DescribeInstances
                    - ec2:CreateNetworkInterface
                    - ec2:AttachNetworkInterface
                    - ec2:DeleteNetworkInterface
                    - ec2:DetachNetworkInterface
                    - ec2:ModifyNetworkInterfaceAttribute
                    - ec2:AssignPrivateIpAddresses
                    - tag:TagResources
                  Resource: "*"
          - 
            PolicyName: eks
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - 
                  Effect: Allow
                  Action:
                    - eks:DescribeCluster
                  Resource: "*"
          - 
            PolicyName: s3-management
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - 
                  Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:ListBucket
                    - s3:DeleteObject
                  Resource:
                    - Fn::GetAtt: [ S3BucketAwseksspotserverlessdemodevuploads, Arn ]
                    - Fn::Join:
                        - "/"
                        -
                          - Fn::GetAtt: [ S3BucketAwseksspotserverlessdemodevuploads, Arn ]
                          - "*"
                - 
                  Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:ListBucket
                    - s3:DeleteObject
                  Resource:
                    - Fn::GetAtt: [ S3BucketAwseksspotserverlessdemodevthumbnails, Arn ]
                    - Fn::Join:
                        - "/"
                        -
                          - Fn::GetAtt: [ S3BucketAwseksspotserverlessdemodevthumbnails, Arn ]
                          - "*"
                - 
                  Effect: Allow
                  Action:
                    - s3:HeadBucket
                  Resource: '*'
          - 
            PolicyName: ClusterAutoscaler
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action:
                    - ec2:DescribeRegions
                    - ec2:DescribeInstances
                  Resource: "*"
                -
                  Effect: Allow
                  Action:
                    - ecr:GetAuthorizationToken
                    - ecr:BatchCheckLayerAvailability
                    - ecr:GetDownloadUrlForLayer
                    - ecr:GetRepositoryPolicy
                    - ecr:DescribeRepositories
                    - ecr:ListImages
                    - ecr:BatchGetImage
                  Resource: "*"
                -
                  Effect: Allow
                  Action:
                    - autoscaling:DescribeAutoScalingGroups
                    - autoscaling:DescribeAutoScalingInstances
                    - autoscaling:DescribeLaunchConfigurations
                    - autoscaling:SetDesiredCapacity
                    - autoscaling:DescribeTags
                    - autoscaling:TerminateInstanceInAutoScalingGroup
                  Resource: "*"
    NodeInstanceProfile:
      Type: AWS::IAM::InstanceProfile
      Properties:
        Path: "/"
        Roles:
          - Ref: NodeInstanceRole
    NodeSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Security group for all nodes in the EKS cluster
        VpcId:
          Ref: KubernetesClusterVPC
        Tags:
          -
            Key: Name
            Value: ${self:service}-${self:provider.stage}
    NodeSecurityGroupIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        Description: Allow node to communicate with each other
        GroupId:
          Ref: NodeSecurityGroup
        SourceSecurityGroupId:
          Ref: NodeSecurityGroup
        IpProtocol: '-1'
        FromPort: 0
        ToPort: 65535
    NodeSecurityGroupFromWorkstationIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        Description: Allow workstation to connect to EC2 nodes (for debugging)
        GroupId:
          Ref: NodeSecurityGroup
        IpProtocol: 'tcp'
        FromPort: 22
        ToPort: 22
        CidrIp: 138.68.101.60/32
    NodeSecurityGroupFromControlPlaneIngress:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        Description: Allow worker Kubelets and pods to receive communication from the cluster control plane
        GroupId:
          Ref: NodeSecurityGroup
        SourceSecurityGroupId:
          Ref: KubernetesClusterMasterSecurityGroup
        IpProtocol: tcp
        FromPort: 1025
        ToPort: 65535
    KubernetesClusterMasterSecurityGroupIngressFromNodes:
      Type: AWS::EC2::SecurityGroupIngress
      Properties:
        Description: Allow pods to communicate with the cluster API Server
        GroupId:
          Ref: KubernetesClusterMasterSecurityGroup
        SourceSecurityGroupId:
          Ref: NodeSecurityGroup
        IpProtocol: tcp
        ToPort: 443
        FromPort: 443
    SpotNodeLaunchConfig:
      Type: AWS::AutoScaling::LaunchConfiguration
      Properties:
        AssociatePublicIpAddress: true
        # https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html
        ImageId: ami-0a0b913ef3249b655
        InstanceType: m3.medium
        IamInstanceProfile:
          Ref: NodeInstanceProfile
        KeyName: 'Lenovo T410'
        # Maximum Spot instance price (not launch if more)
        SpotPrice: 1
        SecurityGroups:
          - Ref: NodeSecurityGroup
        UserData:
          Fn::Base64:
            Fn::Join:
              - ""
              -
                - "#!/bin/bash -xe\n"
                - "set -o xtrace"
                - "\n"
                - Fn::Join:
                  - " "
                  -
                    - "/etc/eks/bootstrap.sh"
                    - Ref: KubernetesCluster
                - "\n"
                - "/opt/aws/bin/cfn-signal -e $? "
                - "         --stack ${self:service}-${self:provider.stage} "
                - "         --resource NodeGroup "
                - "         --region ${self:provider.region}"
    SpotNodeGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        DesiredCapacity: 1
        LaunchConfigurationName:
          Ref: SpotNodeLaunchConfig
        # To allow rolling updates
        MinSize: 0
        MaxSize: 2
        VPCZoneIdentifier:
          - Ref: KubernetesClusterSubnetA
          - Ref: KubernetesClusterSubnetB
        Tags:
          -
            Key: Name
            Value: ${self:service}-${self:provider.stage}
            PropagateAtLaunch: true
          - Key:
              Fn::Join:
                - "/"
                -
                  - "kubernetes.io"
                  - "cluster"
                  - "${self:service}-${self:provider.stage}"
            Value: 'owned'
            PropagateAtLaunch: 'true'
      UpdatePolicy:
        AutoScalingRollingUpdate:
          MinInstancesInService: 0
          MaxBatchSize: 1
      
        
  Outputs:
    KubernetesClusterName:
      Description: "EKS Cluster Name"
      Value:
        Ref: KubernetesCluster
    KubernetesClusterEndpoint:
      Description: "EKS Cluster Endpoint"
      Value:
        Fn::GetAtt: [ KubernetesCluster, Endpoint ]
    KubernetesClusterCertificateAuthorityData:
      Description: "EKS Cluster Certificate Authority Data"
      Value:
        Fn::GetAtt: [ KubernetesCluster, CertificateAuthorityData ]
    KubernetesClusterNodesRoleArn:
      Description: "EKS Cluster Nodes Role Arn"
      Value:
        Fn::GetAtt: [ NodeInstanceRole, Arn ]
    LambdaFunctionsRoleArn:
      Description: "Lambda Functions Role Arn"
      Value:
        Fn::GetAtt: [ IamRoleLambdaExecution, Arn ]


